### ISSUE TITLE
чооо тискудев я твой фанат дай афтограф пжпжпжпжжппжпжжпжп

### ISSUE THREAD

**Issue by cotikyt** [tickydev/mountain-client#1]
чооо тискудев я твой фанат дай афтограф пжпжпжпжжппжпжжпжпчооо тискудев я твой фанат дай афтограф пжпжпжпжжппжпжжпжпчооо тискудев я твой фанат дай афтограф пжпжпжпжжппжпжжпжпчооо тискудев я твой фанат дай афтограф пжпжпжпжжппжпжжпжпчооо тискудев я твой фанат дай афтограф пжпжпжпжжппжпжжпжпчооо тискудев я твой фанат дай афтограф пжпжпжпжжппжпжжпжпчооо тискудев я твой фанат дай афтограф пжпжпжпжжппжпжжпжпчооо тискудев я твой фанат дай афтограф пжпжпжпжжппжпжжпжпчооо тискудев я твой фанат дай афтограф пжпжпжпжжппжпжжпжпчооо тискудев я твой фанат дай афтограф пжпжпжпжжппжпжжпжп

**Comment by tickydev** [comment]
потом

**Comment by tickydev** [comment]
в телеграме жоский автограф будет
